#!/usr/bin/env python3
"""Receipt index generator/validator for the managerial-output-vs-industry-structure
eval case.

Stdlib only. Builds a public-safe index of the case's model-output receipts from
the model-output frontmatter and the score-sheet per-run tables. The index
*points to* receipts — it records where each receipt is and its provenance — and
does not summarise the model outputs away. A model output is a test artifact,
never an authority.

Modes:
- (default) generate — (re)write receipt-index.yaml in the case folder.
- --check          — recompute the index and report any drift from the file
                     on disk; writes nothing.

Both modes are read-only with respect to model outputs, scores, and statuses,
make no model/API calls, and read no raw source files.
"""

from __future__ import annotations

from pathlib import Path
import re
import sys

from artifact_status import read_frontmatter
from eval_lab_status import classify_output

ROOT = Path(__file__).resolve().parents[1]
CASE_DIR = ROOT / "evals/contradiction-preservation/managerial-output-vs-industry-structure"
INDEX_PATH = CASE_DIR / "receipt-index.yaml"


def run_number(stem: str) -> int:
    """Run number from a model-output filename stem: '<cond>'=1, '<cond>-NN'=NN."""
    m = re.search(r"-(\d+)$", stem)
    return int(m.group(1)) if m else 1


def condition_of(stem: str) -> str:
    return re.sub(r"-\d+$", "", stem)


def parse_run_scores(score_sheet: Path) -> dict[tuple[int, str], str]:
    """Parse per-run, per-condition scores from the score-sheet's run tables."""
    scores: dict[tuple[int, str], str] = {}
    if not score_sheet.is_file():
        return scores
    current_run: int | None = None
    header: list[str] | None = None
    for raw in score_sheet.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if s.startswith("#"):
            m = re.match(r"#+\s*Run\s+0*(\d+)\b", s)
            current_run = int(m.group(1)) if m else None
            header = None
            continue
        if current_run is None or not s.startswith("|"):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if not cells:
            continue
        if cells[0] == "Criterion":
            header = cells[1:]
        elif "Per-condition score" in cells[0] and header is not None:
            for cond, val in zip(header, cells[1:]):
                scores[(current_run, cond)] = val
    return scores


def build_receipts() -> list[dict]:
    """One index entry per model-output file in the case folder."""
    scores = parse_run_scores(CASE_DIR / "score-sheet.md")
    outputs_dir = CASE_DIR / "model-outputs"
    receipts: list[dict] = []
    if not outputs_dir.is_dir():
        return receipts
    for path in sorted(outputs_dir.glob("*.md")):
        fm = read_frontmatter(path)
        stem = path.stem
        cond = (fm.get("model_condition") or condition_of(stem)).strip()
        rnum = run_number(stem)
        score = scores.get((rnum, cond), "")
        receipts.append({
            "run_id": fm.get("run_id") or stem,
            "condition": cond,
            "run_number": rnum,
            "seed": fm.get("seed") or "",
            "model_id": fm.get("model_id") or fm.get("model_name") or "",
            "source_packet_sha256": fm.get("source_packet_sha256") or "",
            "output_file": f"model-outputs/{path.name}",
            "classification": classify_output(fm),
            "score": score or "(unscored)",
            "judge_model_id": fm.get("judge_model_id") or "",
        })
    receipts.sort(key=lambda r: (r["condition"], r["run_number"]))
    return receipts


FIELD_ORDER = [
    "run_id", "condition", "run_number", "seed", "model_id",
    "source_packet_sha256", "output_file", "classification", "score",
    "judge_model_id",
]


def render_index(receipts: list[dict]) -> str:
    lines = [
        "# Receipt index — managerial-output-vs-industry-structure",
        "# Generated by scripts/receipt_index.py (make receipt-index).",
        "# A public-safe index of model-output receipts: it points to each receipt",
        "# and records its provenance. It does not summarise the model outputs away.",
        "# A model output is a test artifact, never an authority and never citable",
        "# as a source. Regenerate with `make receipt-index`; validate with",
        "# `python3 scripts/receipt_index.py --check`.",
        "case_id: managerial-output-vs-industry-structure",
        "generated_by: scripts/receipt_index.py",
        f"receipt_count: {len(receipts)}",
        "receipts:",
    ]
    for r in receipts:
        first = True
        for key in FIELD_ORDER:
            val = r[key]
            rendered = "" if val == "" else str(val)
            prefix = "  - " if first else "    "
            lines.append(f"{prefix}{key}: {rendered}")
            first = False
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    receipts = build_receipts()
    rendered = render_index(receipts)

    print("== Anti-Slop receipt index — managerial-output-vs-industry-structure ==")
    if not receipts:
        print("No model-output receipts found in the case folder.")
        return 0

    if check:
        existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.is_file() else ""
        if not existing:
            print(f"--check: {INDEX_PATH.relative_to(ROOT)} does not exist; "
                  f"run `make receipt-index` to generate it.")
        elif existing == rendered:
            print(f"--check: {INDEX_PATH.relative_to(ROOT)} is up to date "
                  f"({len(receipts)} receipts).")
        else:
            print(f"--check: {INDEX_PATH.relative_to(ROOT)} is STALE — "
                  f"regenerate with `make receipt-index`.")
        print("Read-only; nothing written.")
    else:
        INDEX_PATH.write_text(rendered, encoding="utf-8")
        print(f"Wrote {INDEX_PATH.relative_to(ROOT)} ({len(receipts)} receipts).")

    by_cond: dict[str, int] = {}
    real = sum(1 for r in receipts if r["classification"] == "real")
    sim = sum(1 for r in receipts if r["classification"] == "simulated")
    unk = sum(1 for r in receipts if r["classification"] == "unknown")
    for r in receipts:
        by_cond[r["condition"]] = by_cond.get(r["condition"], 0) + 1
    print(f"Receipts: {len(receipts)} — {real} real, {sim} simulated, {unk} unclassified.")
    print("By condition: " + ", ".join(f"{c}×{n}" for c, n in sorted(by_cond.items())))
    print("The index points to receipts; it does not replace them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
